repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/diffplug/spotless
    rev: v6.25.0
    hooks:
      - id: spotless-gradle
        name: Format Java code
        entry: ./gradlew spotlessApply
        language: system

  - repo: local
    hooks:
      - id: eslint
        name: Lint React Native
        entry: npm run lint
        language: node
        types: [javascript, ts, tsx]
