name: App CI

on:
  push:
    branches: [main, develop]
    paths:
      - "app/**"
      - ".github/workflows/app-ci.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "app/**"
      - ".github/workflows/app-ci.yml"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run ESLint
        run: |
          cd app
          npm run lint

      - name: Run TypeScript type check
        run: |
          cd app
          npm run type-check

      - name: Run Prettier check
        run: |
          cd app
          npm run format:check

      - name: Run tests
        run: |
          cd app
          npm test -- --coverage --watchAll=false

      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./app/coverage/lcov.info
          flags: app

      - name: Build app
        run: |
          cd app
          npx expo export --platform all

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-build
          path: app/dist/
          retention-days: 7
