name: Server CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x server/gradlew

      - name: Check code style with Checkstyle
        run: |
          cd server
          ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        run: |
          cd server
          ./gradlew test --no-daemon
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/myapp_test
          SPRING_DATASOURCE_USERNAME: test_user
          SPRING_DATASOURCE_PASSWORD: test_password

      - name: Build with Gradle
        run: |
          cd server
          ./gradlew build -x test --no-daemon

      - name: Generate test coverage report
        run: |
          cd server
          ./gradlew jacocoTestReport

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./server/build/reports/jacoco/test/jacocoTestReport.xml
          flags: server

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: server-jar
          path: server/build/libs/*.jar
          retention-days: 7

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: server/build/test-results/
          retention-days: 7
